version: "3.5"

services:
  validator:
    image: odinprotocol/core:v0.4.0
    container_name: validator
    restart: always
    deploy:
      resources:
        limits:
          memory: 1800m
        reservations:
          memory: 1000m
    ports:
      - 26658:26658
      - 26657:26657
      - 26656:26656
      - 9090:9090
      - 1317:1317
    command: cosmovisor run start
    environment:
      - DAEMON_NAME=odind
      - DAEMON_HOME=/root/.odin
    networks:
      default:
        ipv4_address: 172.18.0.2
    volumes:
      - vol:/root/.odin
      - ./node_key.json:/root/.odin/config/node_key.json
      - ./priv_validator_key.json:/root/.odin/config/priv_validator_key.json

  yoda:
    image: odinprotocol/core:v0.4.0
    container_name: yoda
    depends_on:
      - validator
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.3
    command: sh -c "yoda run --log-level debug --node tcp://172.18.0.2:26657"
    volumes:
      - ../.yoda:/root/.yoda

volumes:
  vol:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
